### ISSUE TITLE
Invocation Failed

### ISSUE THREAD

**Issue by titorgla** [gabor-kovacs/the-kanji-map#12]
# TypeError Conversion
![Screenshot from 2024-05-05 16-57-47](https://github.com/gabor-kovacs/the-kanji-map/assets/88099383/81e07796-59b1-4973-b446-2eefc05d307e)

# Also What happened?
I have been using this site for well over 2 years with no issue whatsoever it's a great resource but what happened to https://thekanjimap.com/, why the migration to https://thekanjimap.netlify.app/. I have been recommending this app to peers and learners for a long time is this a thing I should be worried about?

**Comment by gabor-kovacs** [comment]
hello, can you provide a link of the page that threw the error?
https://thekanjimap.netlify.app was always an active mirror of the site, the error is unrelated to the domain
this is a hobby project and I no longer wish to pay for the domain name, but it will remain active in some form anyway
nevertheless I removed the alert dialog because it is annoying and I might change my mind about keeping the domain

**Comment by titorgla** [comment]
Hi, yes I am not that aware of anything different that I am doing to get this error, I just search for the kanji as usual using the search box and it would always display the results but 2 or so days ago I've been getting this error

> can you provide a link of the page that threw the error?

I am afraid that's not possible as it would display (or redirect?) to the same error page of whatever the kanji I selected, here's a screen capture 

[Screencast from Monday, 06 May, 2024 12:54:50 AM.webm](https://github.com/gabor-kovacs/the-kanji-map/assets/88099383/37c5e5c0-4668-41cb-a94f-2c0e4917dc1b)

Here is the entire printout of the `Stack trace` text-box

```
TypeError: Cannot convert argument to a ByteString because the character at index 6 has a value of 20840 which is greater than 255.
    at webidl.converters.ByteString (node:internal/deps/undici/undici:1834:17)
    at _Headers.set (node:internal/deps/undici/undici:2164:35)
    at setCacheTagsHeaders (file:///var/task/.netlify/dist/run/headers.js:188:13)
    at file:///var/task/.netlify/dist/run/handlers/server.js:3326:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async server_default (file:///var/task/.netlify/dist/run/handlers/server.js:3298:10)
    at async file:///var/task/___netlify-server-handler.mjs:33:24
    at async Module.handler (file:///var/task/___netlify-server-handler.mjs:21:27)
    at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:3734:15)
    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)
```
The only data that would change is the `value of [X]` which would change everytime I input a new kanji

> [thekanjimap.netlify.app](https://thekanjimap.netlify.app/) was always an active mirror of the site, the error is unrelated to the domain this is a hobby project and I no longer wish to pay for the domain name

Oh ok thanks for the clarification

**Comment by Jirachi145** [comment]
Came here to add a little information; also having the same error. Testing, this occurs on both thekanjimap.com and thekanjimap.netlify.app domains, and seems that every search causes it. The /about subpage still works, so this is specifically the search function + kanji pages.

**Comment by gabor-kovacs** [comment]
seems like the issue is with the new netlify next.js runtime v5
i deployed it with v4 and seems to be working

**Comment by Jirachi145** [comment]
Yes, that seems to have fixed the issue for me as well.
