### ISSUE TITLE
Most kanji map nodes aren't clickable in Brave browser.

### ISSUE THREAD

**Issue by christopherball** [gabor-kovacs/the-kanji-map#13]
Not sure if compatibility with all chromium-based browsers is intended, but the majority of the kanji map nodes aren't clickable in Brave for some reason.

**Comment by gabor-kovacs** [comment]
Can you reproduce this somehow? I installed brave on win11 and everything works fine.

**Comment by gabor-kovacs** [comment]
I see I was trying the 3D nodes only. 

Same problem with brave on windows here.

Related issues: [1](https://github.com/vasturiano/force-graph/issues/177), [2](https://github.com/oleeskild/obsidian-digital-garden/issues/103), [3](https://github.com/vasturiano/force-graph/issues/247)

It looks like that node hover state is checked via canvas color but brave purposefully reports wrong values for privacy/fingerprint protection.

You can uncheck "block fingerprinting" in the brave shields menu at the search bar for the site and it should work.
