### ISSUE TITLE
Usability suggestion: freeze 3D map on mouseover

### ISSUE THREAD

**Issue by onlyjob** [gabor-kovacs/the-kanji-map#14]
3D view would be more usable if animation stops when mouse cursor hovers over kanji.

Event already triggers to show reading and translation on mouse hover, but it could be hard to keep tracking kanji with the mouse to keep translation visible. IMHO 3D animation should stop when translation is displayed, and resume when mouse moves away from kanji.

Please consider such minor improvement. Thanks.

**Comment by gabor-kovacs** [comment]
added this, thanks for the suggestion

**Comment by onlyjob** [comment]
Perfect, thank you.

**Comment by onlyjob** [comment]
Minor pedantic follow-up that may not be worthy of its own issue:
Perhaps it would be even better to delay resume of animation for about 0.5 second.
This is because map shakes when cursor moves from kanji to kanji, when animation resumes for a fraction of a second. 
(It is probably not worth the effort if implementation is not trivial.)
Thanks.
