### ISSUE TITLE
誨 is 言+每, is it not?

### ISSUE THREAD

**Issue by onlyjob** [gabor-kovacs/the-kanji-map#17]
`誨` (https://thekanjimap.com/%E8%AA%A8) is shown as `言+毎` which looks incorrect to me, because `言+每` is probably more accurate.

`每` is `母`+`𠂉` (Radical number 9 https://www.kanshudo.com/kanji/%F0%A0%82%89)

However _theKanjiMap_ don't know `每` (https://thekanjimap.com/%E6%AF%8F)
which is known to Jisho: https://jisho.org/search/%E6%AF%8F%20%23kanji

Is this an issue with dataset? Where it would be best to report such issues?

I am a bit confused... Did I miss something?

**Comment by gabor-kovacs** [comment]
`毎` and `每` are 2 variants of the same glyph the 2 small strokes were probably simplified to 1 at some point, see [https://en.glyphwiki.org/wiki/u6bce](url)

I create the decomposition and graphs from the kanjivg.xml file automatically and I do not intend to manually adjust anything in it.
The point of these graphs and decompositions is to see connections and I think separating these would just miss the important part, but if you still feel like these two characters should be separate you can write an issue to kanjivg on github. If a new version is released I can update the app using that.

**Comment by onlyjob** [comment]
Makes sense, thanks.
