### ISSUE TITLE
Arrows not visible in dark mode in 2D view.

### ISSUE THREAD

**Issue by U-990i** [gabor-kovacs/the-kanji-map#20]
In dark mode in the 2D view, arrows and direction of arrows are not visible. 

<img width="484" alt="Screenshot" src="https://github.com/user-attachments/assets/2978435a-2f6d-4c2a-9eaa-17b1b1e95b81">

System - Mac M1 
Browser - Chrome : Version 129.0.6668.91

**Comment by gabor-kovacs** [comment]
should be fixed now

**Comment by U-990i** [comment]
@gabor-kovacs Oh wow you work fast. Thank you for this. I was looking for something like this. I will see if it helps me remember Kanji.
