### ISSUE TITLE
Disable the "marching ants" effect on the arrows?

### ISSUE THREAD

**Issue by lazarljubenovic** [gabor-kovacs/the-kanji-map#21]
...or "particles", as I [see](https://github.com/gabor-kovacs/the-kanji-map/blob/main/src/components/graph-2D.tsx#L237-L242) it's called in the source code. It's really distracting for me, especially when there's a lot of edges, like https://thekanjimap.com/%E8%99%AB. I personally don't see the benefit of them at all, so I'd just get rid of them altogether, but at least an option to toggle it?

**Comment by gabor-kovacs** [comment]
added a toggle for this
