### ISSUE TITLE
Body overflow hidden makes things unreadable / unreachable

### ISSUE THREAD

**Issue by Karmak23** [gabor-kovacs/the-kanji-map#4]
I don’t understand while the website has `overflow: hidden` on body, which makes many things unreachable on every of my devices (android phone, tablet, even notebook PC). I must un-zoom to unreadable sizes for everything to fit on screen.

Could you please either remove the attribute on the website or explain why it’s so ?
best regards

**Comment by gabor-kovacs** [comment]
Could you tell me what browsers you are using?
`overflow: hidden` is used to hide the scroll bars, but everything should fit exactly to the screen
