### ISSUE TITLE
[Firefox] Kanji Graph viewport not visible / does not expand to height of browser window

### ISSUE THREAD

**Issue by ika-musuko** [gabor-kovacs/the-kanji-map#8]
First of all, thank you for creating such a helpful study tool!

For reference, I am using Firefox 118.0.2 on Mac OS X 10.15.
This is not a problem in Chrome, but it is a problem in Firefox. 

The kanji graph viewport seems to not expand all the way to the bottom of the webpage.
<img width="898" alt="スクリーンショット 2023-10-26 20 38 53" src="https://github.com/gabor-kovacs/the-kanji-map/assets/32429059/a11a761c-054b-4b1e-9ee2-09a9c2d03179">

This scenario is not quite a world-ender, but the page would definitely look better if it did expand to the bottom like it does in Chrome.

The worst case scenario is when a kanji has no examples, completely hiding the graph and rendering the app unusable.
<img width="898" alt="スクリーンショット 2023-10-26 20 37 04" src="https://github.com/gabor-kovacs/the-kanji-map/assets/32429059/244f5c3b-7a9b-4034-b01c-17a1b6909457">

I believe the issue is with the ```height: -moz-available``` css declaration. I'm not sure what the expected behavior of this declaration is, but the usage of the declaration here seems to be the main culprit.

current webpage (with ```-moz-available``` enabled)
<img width="891" alt="スクリーンショット 2023-10-26 20 29 18" src="https://github.com/gabor-kovacs/the-kanji-map/assets/32429059/7cf61bdb-1bcb-4def-b6bd-562644ff6a3d">

If you disable the ```height: -moz-available``` on the "container" div, then the css resolves ```height``` to ```100vh```, and the page looks as expected.

<img width="898" alt="スクリーンショット 2023-10-26 20 45 01" src="https://github.com/gabor-kovacs/the-kanji-map/assets/32429059/0fbc90a0-10a6-4a61-b66e-258eec74e3b1">
<img width="898" alt="スクリーンショット 2023-10-26 20 45 52" src="https://github.com/gabor-kovacs/the-kanji-map/assets/32429059/c1e8073c-a833-4d4c-b6d1-f806e7224bd9">

**Comment by gabor-kovacs** [comment]
Hi,
Thank you for pointing out the problem and also finding the culprit.
The fill-available prop was added so that the screen fits webkit based mobile browsers (safari) between the toolbars.
I left the webkit prefixed prop and deleted others, not it works on firefox too as intended.

**Comment by ika-musuko** [comment]
This works as expected now. Thank you for the prompt fix!
